export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = '"GET_PRODUCTS_SUCCESS"';
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
